kind: pipeline
type: docker
name: build
steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  pull: if-not-exists # always never
  commands:
    - dotnet restore
    - dotnet publish -r linux-x64 -c Release -o /cache/out
trigger:
  branch:
  - dev
  - master
